### ISSUE TITLE
Umlaute im Ordnernamen führen zu Problemen mit Vagrant auf Windows

### ISSUE THREAD

**Issue by marcohald** [ansible-buch/listings#1]
Durch den Umlaut im Ordnernamen 01-Einführung_und_Installation kommt es zu einem Problem mit dem Vagrant index File.

Siehe https://github.com/hashicorp/vagrant/issues/12455 und https://github.com/hashicorp/vagrant/issues/10657#issuecomment-660937548

Nach einer Umbenennung in 01-Einfuehrung_und_Installation funktioniert es problemlos.

Der Fehler liegt zwar eindeutig bei Vagrant, eine Umbenennung macht meiner Meinung nach trotzdem Sinn.

**Comment by ansible-buch** [comment]
Habe den Ordnernamen wie vorgeschlagen umbenannt. Für die 2. Auflage werde ich das im Generierungsprozess
ändern. Vielen Dank für den Hinweis!
