### ISSUE TITLE
Windows 11 Vagrant up schlägt fehl 

### ISSUE THREAD

**Issue by Aramorth** [ansible-buch/listings#2]
PS D:\Users\XXX\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation> vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: incompatible character encodings: CP850 and Windows-1252
PS D:\Users\XXX\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation>
PS D:\Users\XXX\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation>   vagrant plugin repair
Repairing currently installed global plugins. This may take a few minutes...
Installed plugins successfully repaired!
PS D:\Users\XXX\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation> vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: incompatible character encodings: CP850 and Windows-1252
PS D:\Users\XXX\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation> vagrant plugin expunge --reinstall

This command permanently deletes all currently installed user plugins. It
should only be used when a repair command is unable to properly fix the
system.

Continue? [N]: Y

All user installed plugins have been removed from this Vagrant environment!

Vagrant will now attempt to reinstall user plugins that were removed.
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Fetching micromachine-3.0.0.gem
Fetching vagrant-vbguest-0.30.0.gem
Installed the plugin 'vagrant-vbguest (0.30.0)'!
PS D:\Users\XXX\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation> vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: incompatible character encodings: CP850 and Windows-1252
PS D:\Users\XXX\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation> PS D:\Users\Bjoer\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation> vagrant up
Get-Process: A positional parameter cannot be found that accepts argument 'vagrant'.
PS D:\Users\XXX\Downloads\978-3-8362-7660-3\listings\01-Einführung_und_Installation> Vagrant failed to initialize at a very early stage:
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

**Comment by ansible-buch** [comment]
That was probably a problem with German Umlauts. I think I fixed this.
Beware: Since today all the listings are from the 2nd edition. See the 'erste-auflage' tag for the "old" listings.
