### ISSUE TITLE
Vagrant up with VirtualBox >= 6.1.28 network access error [fix included]

### ISSUE THREAD

**Issue by Bravd42** [ansible-buch/listings#3]
Hi,

ich arbeite gerade das Buch durch und bin auf einen kleinen Haken gestoßen. Die Vagrant Datei aus Kapitel 1 funktioniert so nicht mehr, da nur Netzwerke in der IP range 192.168.56.0/21 erlaubt sind:

> ==> ansible: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
> Command: ["hostonlyif", "ipconfig", "vboxnet2", "--ip", "192.168.150.1", "--netmask", "255.255.255.0"]
> Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
> VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file 
> VBoxManageHostonly.cpp

Es gibt aber die Möglichkeit andere Netze zu erlauben. Der fix für mich war:

`echo "* 192.168.150.0/24" > /etc/vbox/networks.conf`

Alle Netze erlauben:

`echo "* * 0.0.0.0/0 ::/0" >> /etc/vbox/networks.conf`

Getestet auf Debian 11.

Hier noch die Doku von Virtualbox: https://www.virtualbox.org/manual/ch06.html#network_hostonly
und der rettende Hinweis kam von hier: https://stackoverflow.com/a/69768235

Gruß
Bravd

**Comment by ansible-buch** [comment]
Hallo Bravd,

danke für den Hinweis! Ich arbeite hier ebenfalls mit einem Debian 11-Desktop und bin schon lange genervt, weil mich VirualBox immer zu einem 192.168.57.1er Netzwerk "gezwungen" hat :-(

Habe jetzt auch eine `networks.conf` mit `0.0.0.0/0` drin. Ich glaube, in Ihrer echo-Zeile ist aber ein "*" zuviel?
Bei mir klappt's jetzt jedenfalls mit

```
* 0.0.0.0/0 ::/0
```

Viele Grüße,
  Axel

**Comment by ansible-buch** [comment]
Es heißt "VirtualBox" ;-) Für alles andere nehme ich übrigens VMware...

**Comment by Bravd42** [comment]
Hi,

ja, da ist ein '*' zuviel drin.

Gruß
Bravd
