### ISSUE TITLE
Passwörter der VM´s funktionieren nicht Buch version 1

### ISSUE THREAD

**Issue by Aramorth** [ansible-buch/listings#5]
Hallo ich habe das Buch Auflage 1 und wollte gerne die Laborumgebung nutzen diese funktioniert wohl nicht mit den angegebenen Passwörter im Buch nicht mehr. Bitte teilen Sie mir die Passwörter mit.

**Comment by ansible-buch** [comment]
Hallo Aramorth,
verwenden Sie denn sicher die Listings passend zur 1. Auflage? Ein ähnliches Problem gab es auch hier: https://github.com/ansible-buch/listings/issues/4
Neuerdings (d.h. in Auflage 2) sind die Vagrant-VMs unverändert provisioniert, also mit User "vagrant" und Passwort "vagrant". (Dieser hat dann sudo-Rechte.) Sie können natürlich auch damit ein Inventory aufbauen, aber wenn später auch weitere Listings nicht passen, macht das auch keinen Spaß.
